/// Flutter icons PicPay
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PicPay
///      fonts:
///       - asset: fonts/PicPay.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PicPay {
  PicPay._();

  static const _kFontFam = 'PicPay';

  static const IconData house_black_silhouette_without_door = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData credit_card = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData notification = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData follow = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData qr_code = const IconData(0xe805, fontFamily: _kFontFam);
}
